namespace SharedComponent
{
    [default_interface]
     runtimeclass App : Windows.UI.Xaml.Application, Windows.UI.Xaml.Markup.IXamlMetadataProvider, Windows.Foundation.IClosable
     {
        App();
     }
}
